# Where things are
source:       .
destination:  ./_site
plugins:      ./_plugins
layouts:      ./_layouts
paginate:     8

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts:  null
limit_posts:  0
future:       true
unpublished:  false

# Conversion
markdown:     kramdown
highlighter:  pygments
lsi:          false
excerpt_separator: "\n\n"

# Serving
detach:       false
port:         4000
host:         localhost
baseurl:      "" # does not include hostname

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null

# Basic
title: Awarrior
subTitle: The hard part isn’t making the decision. It’s living with it.
description: Awarrior
#url: http://localhost:4000 
url: http://awarrior.github.io
feed: /atom.xml

# Settings
nav:
  - text: Home
    url: /index.html
    icon: icon-home
    class: home
  - text: Archives
    url: /archives.html
    icon: icon-reorder
    class: none
  - text: Github
    url: https://github.com/awarrior
    icon: icon-github
    class: none
  - text: Links
    url: /links.html
    icon: icon-heart
    class: none
  - text: Author
    url: /contact.html
    icon: icon-user
    class: none

page:
  - text: Archives
    url: /archives.html
    last: true
  - text: Github
    url: https://github.com/awarrior
    last: true
  - text: Links
    url: /links.html
    last: true
  - text: Author
    url: /contact.html
    last: false

author:
  name: awarrior
